name: leagueapi-test-commons-release-workflow

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    name: leagueapi-test-commons-release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout git
        uses: actions/checkout@v3

      - name: Check version
        uses: avides/actions-project-version-check@v1.4.0
        id: actions_project_version_check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: pom.xml
          only-return-version: true

      - name: Print version check
        run: echo ${{ steps.actions_project_version_check.outputs.version }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.actions_project_version_check.outputs.version }}
          release_name: leagueapi-test-commons-release
          draft: false
          prerelease: false

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -B package --file pom.xml
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
