name: leagueapi-test-commons-quality-workflow

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: commons-quality-check
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    steps:
      - name: Checkout git
        uses: actions/checkout@v3

      - name: Check version
        uses: avides/actions-project-version-check@v1.4.0
        id: actions_project_version_check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: pom.xml

      - name: Print version check result
        run: echo "Version check successful. New Version is:";
          echo ${{ steps.actions_project_version_check.outputs.version }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -B package --file pom.xml
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
